//go:build !ignore_autogenerated

// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Service) DeepCopyInto(out *Service) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Service.
func (in *Service) DeepCopy() *Service {
	if in == nil {
		return nil
	}
	out := new(Service)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Service) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ServiceInitParameters) DeepCopyInto(out *ServiceInitParameters) {
	*out = *in
	if in.AdminEmail != nil {
		in, out := &in.AdminEmail, &out.AdminEmail
		*out = new(string)
		**out = **in
	}
	if in.AlertsEnabled != nil {
		in, out := &in.AlertsEnabled, &out.AlertsEnabled
		*out = new(bool)
		**out = **in
	}
	if in.AppAutoUpdatesEnabled != nil {
		in, out := &in.AppAutoUpdatesEnabled, &out.AppAutoUpdatesEnabled
		*out = new(bool)
		**out = **in
	}
	if in.BackupsEnabled != nil {
		in, out := &in.BackupsEnabled, &out.BackupsEnabled
		*out = new(bool)
		**out = **in
	}
	if in.CustomDomainNames != nil {
		in, out := &in.CustomDomainNames, &out.CustomDomainNames
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.Datacenter != nil {
		in, out := &in.Datacenter, &out.Datacenter
		*out = new(string)
		**out = **in
	}
	if in.DefaultPassword != nil {
		in, out := &in.DefaultPassword, &out.DefaultPassword
		*out = new(string)
		**out = **in
	}
	if in.FirewallEnabled != nil {
		in, out := &in.FirewallEnabled, &out.FirewallEnabled
		*out = new(bool)
		**out = **in
	}
	if in.KeepBackupsOnDeleteEnabled != nil {
		in, out := &in.KeepBackupsOnDeleteEnabled, &out.KeepBackupsOnDeleteEnabled
		*out = new(bool)
		**out = **in
	}
	if in.ProjectID != nil {
		in, out := &in.ProjectID, &out.ProjectID
		*out = new(string)
		**out = **in
	}
	if in.ProviderName != nil {
		in, out := &in.ProviderName, &out.ProviderName
		*out = new(string)
		**out = **in
	}
	if in.RemoteBackupsEnabled != nil {
		in, out := &in.RemoteBackupsEnabled, &out.RemoteBackupsEnabled
		*out = new(bool)
		**out = **in
	}
	if in.ServerName != nil {
		in, out := &in.ServerName, &out.ServerName
		*out = new(string)
		**out = **in
	}
	if in.ServerType != nil {
		in, out := &in.ServerType, &out.ServerType
		*out = new(string)
		**out = **in
	}
	if in.SupportLevel != nil {
		in, out := &in.SupportLevel, &out.SupportLevel
		*out = new(string)
		**out = **in
	}
	if in.SystemAutoUpdatesEnabled != nil {
		in, out := &in.SystemAutoUpdatesEnabled, &out.SystemAutoUpdatesEnabled
		*out = new(bool)
		**out = **in
	}
	if in.SystemAutoUpdatesSecurityPatchesOnlyEnabled != nil {
		in, out := &in.SystemAutoUpdatesSecurityPatchesOnlyEnabled, &out.SystemAutoUpdatesSecurityPatchesOnlyEnabled
		*out = new(bool)
		**out = **in
	}
	if in.TemplateID != nil {
		in, out := &in.TemplateID, &out.TemplateID
		*out = new(float64)
		**out = **in
	}
	if in.Version != nil {
		in, out := &in.Version, &out.Version
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ServiceInitParameters.
func (in *ServiceInitParameters) DeepCopy() *ServiceInitParameters {
	if in == nil {
		return nil
	}
	out := new(ServiceInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ServiceList) DeepCopyInto(out *ServiceList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Service, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ServiceList.
func (in *ServiceList) DeepCopy() *ServiceList {
	if in == nil {
		return nil
	}
	out := new(ServiceList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ServiceList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ServiceObservation) DeepCopyInto(out *ServiceObservation) {
	*out = *in
	if in.AdminEmail != nil {
		in, out := &in.AdminEmail, &out.AdminEmail
		*out = new(string)
		**out = **in
	}
	if in.AdminUser != nil {
		in, out := &in.AdminUser, &out.AdminUser
		*out = new(string)
		**out = **in
	}
	if in.AlertsEnabled != nil {
		in, out := &in.AlertsEnabled, &out.AlertsEnabled
		*out = new(bool)
		**out = **in
	}
	if in.AppAutoUpdatesDayOfWeek != nil {
		in, out := &in.AppAutoUpdatesDayOfWeek, &out.AppAutoUpdatesDayOfWeek
		*out = new(float64)
		**out = **in
	}
	if in.AppAutoUpdatesEnabled != nil {
		in, out := &in.AppAutoUpdatesEnabled, &out.AppAutoUpdatesEnabled
		*out = new(bool)
		**out = **in
	}
	if in.AppAutoUpdatesHour != nil {
		in, out := &in.AppAutoUpdatesHour, &out.AppAutoUpdatesHour
		*out = new(float64)
		**out = **in
	}
	if in.AppAutoUpdatesMinute != nil {
		in, out := &in.AppAutoUpdatesMinute, &out.AppAutoUpdatesMinute
		*out = new(float64)
		**out = **in
	}
	if in.BackupsEnabled != nil {
		in, out := &in.BackupsEnabled, &out.BackupsEnabled
		*out = new(bool)
		**out = **in
	}
	if in.Category != nil {
		in, out := &in.Category, &out.Category
		*out = new(string)
		**out = **in
	}
	if in.City != nil {
		in, out := &in.City, &out.City
		*out = new(string)
		**out = **in
	}
	if in.Cname != nil {
		in, out := &in.Cname, &out.Cname
		*out = new(string)
		**out = **in
	}
	if in.Cores != nil {
		in, out := &in.Cores, &out.Cores
		*out = new(float64)
		**out = **in
	}
	if in.Country != nil {
		in, out := &in.Country, &out.Country
		*out = new(string)
		**out = **in
	}
	if in.CreatedAt != nil {
		in, out := &in.CreatedAt, &out.CreatedAt
		*out = new(string)
		**out = **in
	}
	if in.CreatorName != nil {
		in, out := &in.CreatorName, &out.CreatorName
		*out = new(string)
		**out = **in
	}
	if in.CustomDomainNames != nil {
		in, out := &in.CustomDomainNames, &out.CustomDomainNames
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.Datacenter != nil {
		in, out := &in.Datacenter, &out.Datacenter
		*out = new(string)
		**out = **in
	}
	if in.DefaultPassword != nil {
		in, out := &in.DefaultPassword, &out.DefaultPassword
		*out = new(string)
		**out = **in
	}
	if in.DeploymentEndedAt != nil {
		in, out := &in.DeploymentEndedAt, &out.DeploymentEndedAt
		*out = new(string)
		**out = **in
	}
	if in.DeploymentStartedAt != nil {
		in, out := &in.DeploymentStartedAt, &out.DeploymentStartedAt
		*out = new(string)
		**out = **in
	}
	if in.DeploymentStatus != nil {
		in, out := &in.DeploymentStatus, &out.DeploymentStatus
		*out = new(string)
		**out = **in
	}
	if in.ElestioID != nil {
		in, out := &in.ElestioID, &out.ElestioID
		*out = new(float64)
		**out = **in
	}
	if in.ExternalBackupsEnabled != nil {
		in, out := &in.ExternalBackupsEnabled, &out.ExternalBackupsEnabled
		*out = new(bool)
		**out = **in
	}
	if in.ExternalBackupsRetainDayOfWeek != nil {
		in, out := &in.ExternalBackupsRetainDayOfWeek, &out.ExternalBackupsRetainDayOfWeek
		*out = new(float64)
		**out = **in
	}
	if in.ExternalBackupsUpdateDayOfWeek != nil {
		in, out := &in.ExternalBackupsUpdateDayOfWeek, &out.ExternalBackupsUpdateDayOfWeek
		*out = new(float64)
		**out = **in
	}
	if in.ExternalBackupsUpdateHour != nil {
		in, out := &in.ExternalBackupsUpdateHour, &out.ExternalBackupsUpdateHour
		*out = new(float64)
		**out = **in
	}
	if in.ExternalBackupsUpdateMinute != nil {
		in, out := &in.ExternalBackupsUpdateMinute, &out.ExternalBackupsUpdateMinute
		*out = new(float64)
		**out = **in
	}
	if in.ExternalBackupsUpdateType != nil {
		in, out := &in.ExternalBackupsUpdateType, &out.ExternalBackupsUpdateType
		*out = new(string)
		**out = **in
	}
	if in.FirewallEnabled != nil {
		in, out := &in.FirewallEnabled, &out.FirewallEnabled
		*out = new(bool)
		**out = **in
	}
	if in.FirewallID != nil {
		in, out := &in.FirewallID, &out.FirewallID
		*out = new(string)
		**out = **in
	}
	if in.FirewallPorts != nil {
		in, out := &in.FirewallPorts, &out.FirewallPorts
		*out = new(string)
		**out = **in
	}
	if in.GlobalIP != nil {
		in, out := &in.GlobalIP, &out.GlobalIP
		*out = new(string)
		**out = **in
	}
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(string)
		**out = **in
	}
	if in.IPv4 != nil {
		in, out := &in.IPv4, &out.IPv4
		*out = new(string)
		**out = **in
	}
	if in.IPv6 != nil {
		in, out := &in.IPv6, &out.IPv6
		*out = new(string)
		**out = **in
	}
	if in.KeepBackupsOnDeleteEnabled != nil {
		in, out := &in.KeepBackupsOnDeleteEnabled, &out.KeepBackupsOnDeleteEnabled
		*out = new(bool)
		**out = **in
	}
	if in.LastUpdated != nil {
		in, out := &in.LastUpdated, &out.LastUpdated
		*out = new(string)
		**out = **in
	}
	if in.PricePerHour != nil {
		in, out := &in.PricePerHour, &out.PricePerHour
		*out = new(string)
		**out = **in
	}
	if in.ProjectID != nil {
		in, out := &in.ProjectID, &out.ProjectID
		*out = new(string)
		**out = **in
	}
	if in.ProviderName != nil {
		in, out := &in.ProviderName, &out.ProviderName
		*out = new(string)
		**out = **in
	}
	if in.RAMSizeGb != nil {
		in, out := &in.RAMSizeGb, &out.RAMSizeGb
		*out = new(string)
		**out = **in
	}
	if in.RemoteBackupsEnabled != nil {
		in, out := &in.RemoteBackupsEnabled, &out.RemoteBackupsEnabled
		*out = new(bool)
		**out = **in
	}
	if in.RootAppPath != nil {
		in, out := &in.RootAppPath, &out.RootAppPath
		*out = new(string)
		**out = **in
	}
	if in.ServerName != nil {
		in, out := &in.ServerName, &out.ServerName
		*out = new(string)
		**out = **in
	}
	if in.ServerType != nil {
		in, out := &in.ServerType, &out.ServerType
		*out = new(string)
		**out = **in
	}
	if in.Status != nil {
		in, out := &in.Status, &out.Status
		*out = new(string)
		**out = **in
	}
	if in.StorageSizeGb != nil {
		in, out := &in.StorageSizeGb, &out.StorageSizeGb
		*out = new(float64)
		**out = **in
	}
	if in.SupportLevel != nil {
		in, out := &in.SupportLevel, &out.SupportLevel
		*out = new(string)
		**out = **in
	}
	if in.SystemAutoUpdatesEnabled != nil {
		in, out := &in.SystemAutoUpdatesEnabled, &out.SystemAutoUpdatesEnabled
		*out = new(bool)
		**out = **in
	}
	if in.SystemAutoUpdatesRebootDayOfWeek != nil {
		in, out := &in.SystemAutoUpdatesRebootDayOfWeek, &out.SystemAutoUpdatesRebootDayOfWeek
		*out = new(float64)
		**out = **in
	}
	if in.SystemAutoUpdatesRebootHour != nil {
		in, out := &in.SystemAutoUpdatesRebootHour, &out.SystemAutoUpdatesRebootHour
		*out = new(float64)
		**out = **in
	}
	if in.SystemAutoUpdatesRebootMinute != nil {
		in, out := &in.SystemAutoUpdatesRebootMinute, &out.SystemAutoUpdatesRebootMinute
		*out = new(float64)
		**out = **in
	}
	if in.SystemAutoUpdatesSecurityPatchesOnlyEnabled != nil {
		in, out := &in.SystemAutoUpdatesSecurityPatchesOnlyEnabled, &out.SystemAutoUpdatesSecurityPatchesOnlyEnabled
		*out = new(bool)
		**out = **in
	}
	if in.TemplateID != nil {
		in, out := &in.TemplateID, &out.TemplateID
		*out = new(float64)
		**out = **in
	}
	if in.TrafficIncluded != nil {
		in, out := &in.TrafficIncluded, &out.TrafficIncluded
		*out = new(float64)
		**out = **in
	}
	if in.TrafficIncoming != nil {
		in, out := &in.TrafficIncoming, &out.TrafficIncoming
		*out = new(float64)
		**out = **in
	}
	if in.TrafficOutgoing != nil {
		in, out := &in.TrafficOutgoing, &out.TrafficOutgoing
		*out = new(float64)
		**out = **in
	}
	if in.Version != nil {
		in, out := &in.Version, &out.Version
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ServiceObservation.
func (in *ServiceObservation) DeepCopy() *ServiceObservation {
	if in == nil {
		return nil
	}
	out := new(ServiceObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ServiceParameters) DeepCopyInto(out *ServiceParameters) {
	*out = *in
	if in.AdminEmail != nil {
		in, out := &in.AdminEmail, &out.AdminEmail
		*out = new(string)
		**out = **in
	}
	if in.AlertsEnabled != nil {
		in, out := &in.AlertsEnabled, &out.AlertsEnabled
		*out = new(bool)
		**out = **in
	}
	if in.AppAutoUpdatesEnabled != nil {
		in, out := &in.AppAutoUpdatesEnabled, &out.AppAutoUpdatesEnabled
		*out = new(bool)
		**out = **in
	}
	if in.BackupsEnabled != nil {
		in, out := &in.BackupsEnabled, &out.BackupsEnabled
		*out = new(bool)
		**out = **in
	}
	if in.CustomDomainNames != nil {
		in, out := &in.CustomDomainNames, &out.CustomDomainNames
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.Datacenter != nil {
		in, out := &in.Datacenter, &out.Datacenter
		*out = new(string)
		**out = **in
	}
	if in.DefaultPassword != nil {
		in, out := &in.DefaultPassword, &out.DefaultPassword
		*out = new(string)
		**out = **in
	}
	if in.FirewallEnabled != nil {
		in, out := &in.FirewallEnabled, &out.FirewallEnabled
		*out = new(bool)
		**out = **in
	}
	if in.KeepBackupsOnDeleteEnabled != nil {
		in, out := &in.KeepBackupsOnDeleteEnabled, &out.KeepBackupsOnDeleteEnabled
		*out = new(bool)
		**out = **in
	}
	if in.ProjectID != nil {
		in, out := &in.ProjectID, &out.ProjectID
		*out = new(string)
		**out = **in
	}
	if in.ProviderName != nil {
		in, out := &in.ProviderName, &out.ProviderName
		*out = new(string)
		**out = **in
	}
	if in.RemoteBackupsEnabled != nil {
		in, out := &in.RemoteBackupsEnabled, &out.RemoteBackupsEnabled
		*out = new(bool)
		**out = **in
	}
	if in.ServerName != nil {
		in, out := &in.ServerName, &out.ServerName
		*out = new(string)
		**out = **in
	}
	if in.ServerType != nil {
		in, out := &in.ServerType, &out.ServerType
		*out = new(string)
		**out = **in
	}
	if in.SupportLevel != nil {
		in, out := &in.SupportLevel, &out.SupportLevel
		*out = new(string)
		**out = **in
	}
	if in.SystemAutoUpdatesEnabled != nil {
		in, out := &in.SystemAutoUpdatesEnabled, &out.SystemAutoUpdatesEnabled
		*out = new(bool)
		**out = **in
	}
	if in.SystemAutoUpdatesSecurityPatchesOnlyEnabled != nil {
		in, out := &in.SystemAutoUpdatesSecurityPatchesOnlyEnabled, &out.SystemAutoUpdatesSecurityPatchesOnlyEnabled
		*out = new(bool)
		**out = **in
	}
	if in.TemplateID != nil {
		in, out := &in.TemplateID, &out.TemplateID
		*out = new(float64)
		**out = **in
	}
	if in.Version != nil {
		in, out := &in.Version, &out.Version
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ServiceParameters.
func (in *ServiceParameters) DeepCopy() *ServiceParameters {
	if in == nil {
		return nil
	}
	out := new(ServiceParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ServiceSpec) DeepCopyInto(out *ServiceSpec) {
	*out = *in
	in.ResourceSpec.DeepCopyInto(&out.ResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
	in.InitProvider.DeepCopyInto(&out.InitProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ServiceSpec.
func (in *ServiceSpec) DeepCopy() *ServiceSpec {
	if in == nil {
		return nil
	}
	out := new(ServiceSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ServiceStatus) DeepCopyInto(out *ServiceStatus) {
	*out = *in
	in.ResourceStatus.DeepCopyInto(&out.ResourceStatus)
	in.AtProvider.DeepCopyInto(&out.AtProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ServiceStatus.
func (in *ServiceStatus) DeepCopy() *ServiceStatus {
	if in == nil {
		return nil
	}
	out := new(ServiceStatus)
	in.DeepCopyInto(out)
	return out
}
